@startuml
skinparam defaultTextAlignment center
skinparam ArrowThickness 2
skinparam ActivityBorderThickness 2
skinparam ActivityDiamondBackgroundColor white
skinparam ActivityDiamondBorderThickness 2

|Client|
start
:Fill Booking Form;
:Submit Form;

|System|
:Process Booking;
if () then (success)
  :Show Success Message;
else (failed)
  :Show Error Message;
endif
stop

@enduml 