@startuml
skinparam defaultTextAlignment center
skinparam ArrowThickness 2
skinparam ActivityBorderThickness 2
skinparam ActivityDiamondBackgroundColor white
skinparam ActivityDiamondBorderThickness 2

|Client|
start
:Enter Login Details;

|System|
if () then (success)
  :Access Dashboard;
else (failed)
  :Show Error;
endif
stop

@enduml 